// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/zjutjh/User-Center/biz/dao/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMiniProgramUser(db *gorm.DB, opts ...gen.DOOption) miniProgramUser {
	_miniProgramUser := miniProgramUser{}

	_miniProgramUser.miniProgramUserDo.UseDB(db, opts...)
	_miniProgramUser.miniProgramUserDo.UseModel(&model.MiniProgramUser{})

	tableName := _miniProgramUser.miniProgramUserDo.TableName()
	_miniProgramUser.ALL = field.NewAsterisk(tableName)
	_miniProgramUser.ID = field.NewInt64(tableName, "id")
	_miniProgramUser.StudentID = field.NewString(tableName, "student_id")
	_miniProgramUser.AppType = field.NewString(tableName, "app_type")
	_miniProgramUser.OpenID = field.NewString(tableName, "open_id")
	_miniProgramUser.CreateTime = field.NewTime(tableName, "create_time")
	_miniProgramUser.UpdateTime = field.NewTime(tableName, "update_time")

	_miniProgramUser.fillFieldMap()

	return _miniProgramUser
}

// miniProgramUser 快捷登录表
type miniProgramUser struct {
	miniProgramUserDo miniProgramUserDo

	ALL        field.Asterisk
	ID         field.Int64  // 用户ID
	StudentID  field.String // 学号
	AppType    field.String // 应用类型
	OpenID     field.String // open_id
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (m miniProgramUser) Table(newTableName string) *miniProgramUser {
	m.miniProgramUserDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m miniProgramUser) As(alias string) *miniProgramUser {
	m.miniProgramUserDo.DO = *(m.miniProgramUserDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *miniProgramUser) updateTableName(table string) *miniProgramUser {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.StudentID = field.NewString(table, "student_id")
	m.AppType = field.NewString(table, "app_type")
	m.OpenID = field.NewString(table, "open_id")
	m.CreateTime = field.NewTime(table, "create_time")
	m.UpdateTime = field.NewTime(table, "update_time")

	m.fillFieldMap()

	return m
}

func (m *miniProgramUser) WithContext(ctx context.Context) IMiniProgramUserDo {
	return m.miniProgramUserDo.WithContext(ctx)
}

func (m miniProgramUser) TableName() string { return m.miniProgramUserDo.TableName() }

func (m miniProgramUser) Alias() string { return m.miniProgramUserDo.Alias() }

func (m miniProgramUser) Columns(cols ...field.Expr) gen.Columns {
	return m.miniProgramUserDo.Columns(cols...)
}

func (m *miniProgramUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *miniProgramUser) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 6)
	m.fieldMap["id"] = m.ID
	m.fieldMap["student_id"] = m.StudentID
	m.fieldMap["app_type"] = m.AppType
	m.fieldMap["open_id"] = m.OpenID
	m.fieldMap["create_time"] = m.CreateTime
	m.fieldMap["update_time"] = m.UpdateTime
}

func (m miniProgramUser) clone(db *gorm.DB) miniProgramUser {
	m.miniProgramUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m miniProgramUser) replaceDB(db *gorm.DB) miniProgramUser {
	m.miniProgramUserDo.ReplaceDB(db)
	return m
}

type miniProgramUserDo struct{ gen.DO }

type IMiniProgramUserDo interface {
	gen.SubQuery
	Debug() IMiniProgramUserDo
	WithContext(ctx context.Context) IMiniProgramUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMiniProgramUserDo
	WriteDB() IMiniProgramUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMiniProgramUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMiniProgramUserDo
	Not(conds ...gen.Condition) IMiniProgramUserDo
	Or(conds ...gen.Condition) IMiniProgramUserDo
	Select(conds ...field.Expr) IMiniProgramUserDo
	Where(conds ...gen.Condition) IMiniProgramUserDo
	Order(conds ...field.Expr) IMiniProgramUserDo
	Distinct(cols ...field.Expr) IMiniProgramUserDo
	Omit(cols ...field.Expr) IMiniProgramUserDo
	Join(table schema.Tabler, on ...field.Expr) IMiniProgramUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMiniProgramUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMiniProgramUserDo
	Group(cols ...field.Expr) IMiniProgramUserDo
	Having(conds ...gen.Condition) IMiniProgramUserDo
	Limit(limit int) IMiniProgramUserDo
	Offset(offset int) IMiniProgramUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMiniProgramUserDo
	Unscoped() IMiniProgramUserDo
	Create(values ...*model.MiniProgramUser) error
	CreateInBatches(values []*model.MiniProgramUser, batchSize int) error
	Save(values ...*model.MiniProgramUser) error
	First() (*model.MiniProgramUser, error)
	Take() (*model.MiniProgramUser, error)
	Last() (*model.MiniProgramUser, error)
	Find() ([]*model.MiniProgramUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MiniProgramUser, err error)
	FindInBatches(result *[]*model.MiniProgramUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MiniProgramUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMiniProgramUserDo
	Assign(attrs ...field.AssignExpr) IMiniProgramUserDo
	Joins(fields ...field.RelationField) IMiniProgramUserDo
	Preload(fields ...field.RelationField) IMiniProgramUserDo
	FirstOrInit() (*model.MiniProgramUser, error)
	FirstOrCreate() (*model.MiniProgramUser, error)
	FindByPage(offset int, limit int) (result []*model.MiniProgramUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMiniProgramUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m miniProgramUserDo) Debug() IMiniProgramUserDo {
	return m.withDO(m.DO.Debug())
}

func (m miniProgramUserDo) WithContext(ctx context.Context) IMiniProgramUserDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m miniProgramUserDo) ReadDB() IMiniProgramUserDo {
	return m.Clauses(dbresolver.Read)
}

func (m miniProgramUserDo) WriteDB() IMiniProgramUserDo {
	return m.Clauses(dbresolver.Write)
}

func (m miniProgramUserDo) Session(config *gorm.Session) IMiniProgramUserDo {
	return m.withDO(m.DO.Session(config))
}

func (m miniProgramUserDo) Clauses(conds ...clause.Expression) IMiniProgramUserDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m miniProgramUserDo) Returning(value interface{}, columns ...string) IMiniProgramUserDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m miniProgramUserDo) Not(conds ...gen.Condition) IMiniProgramUserDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m miniProgramUserDo) Or(conds ...gen.Condition) IMiniProgramUserDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m miniProgramUserDo) Select(conds ...field.Expr) IMiniProgramUserDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m miniProgramUserDo) Where(conds ...gen.Condition) IMiniProgramUserDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m miniProgramUserDo) Order(conds ...field.Expr) IMiniProgramUserDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m miniProgramUserDo) Distinct(cols ...field.Expr) IMiniProgramUserDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m miniProgramUserDo) Omit(cols ...field.Expr) IMiniProgramUserDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m miniProgramUserDo) Join(table schema.Tabler, on ...field.Expr) IMiniProgramUserDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m miniProgramUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMiniProgramUserDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m miniProgramUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IMiniProgramUserDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m miniProgramUserDo) Group(cols ...field.Expr) IMiniProgramUserDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m miniProgramUserDo) Having(conds ...gen.Condition) IMiniProgramUserDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m miniProgramUserDo) Limit(limit int) IMiniProgramUserDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m miniProgramUserDo) Offset(offset int) IMiniProgramUserDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m miniProgramUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMiniProgramUserDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m miniProgramUserDo) Unscoped() IMiniProgramUserDo {
	return m.withDO(m.DO.Unscoped())
}

func (m miniProgramUserDo) Create(values ...*model.MiniProgramUser) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m miniProgramUserDo) CreateInBatches(values []*model.MiniProgramUser, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m miniProgramUserDo) Save(values ...*model.MiniProgramUser) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m miniProgramUserDo) First() (*model.MiniProgramUser, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MiniProgramUser), nil
	}
}

func (m miniProgramUserDo) Take() (*model.MiniProgramUser, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MiniProgramUser), nil
	}
}

func (m miniProgramUserDo) Last() (*model.MiniProgramUser, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MiniProgramUser), nil
	}
}

func (m miniProgramUserDo) Find() ([]*model.MiniProgramUser, error) {
	result, err := m.DO.Find()
	return result.([]*model.MiniProgramUser), err
}

func (m miniProgramUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MiniProgramUser, err error) {
	buf := make([]*model.MiniProgramUser, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m miniProgramUserDo) FindInBatches(result *[]*model.MiniProgramUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m miniProgramUserDo) Attrs(attrs ...field.AssignExpr) IMiniProgramUserDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m miniProgramUserDo) Assign(attrs ...field.AssignExpr) IMiniProgramUserDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m miniProgramUserDo) Joins(fields ...field.RelationField) IMiniProgramUserDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m miniProgramUserDo) Preload(fields ...field.RelationField) IMiniProgramUserDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m miniProgramUserDo) FirstOrInit() (*model.MiniProgramUser, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MiniProgramUser), nil
	}
}

func (m miniProgramUserDo) FirstOrCreate() (*model.MiniProgramUser, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MiniProgramUser), nil
	}
}

func (m miniProgramUserDo) FindByPage(offset int, limit int) (result []*model.MiniProgramUser, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m miniProgramUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m miniProgramUserDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m miniProgramUserDo) Delete(models ...*model.MiniProgramUser) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *miniProgramUserDo) withDO(do gen.Dao) *miniProgramUserDo {
	m.DO = *do.(*gen.DO)
	return m
}
