// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/common/excepton.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 业务错误码枚举
type BizCode int32

const (
	// 通用
	BizCode_OK            BizCode = 0
	BizCode_UNKNOWN_ERROR BizCode = 500 // 系统异常，请稍后重试!
	BizCode_PARAM_ERROR   BizCode = 501 // 参数错误
	// 用户相关
	BizCode_PASSWORD_LENGTH_ERROR     BizCode = 401 // 密码长度不符合要求
	BizCode_WRONG_PASSWORD_OR_ACCOUNT BizCode = 402 // 账号或密码错误
	BizCode_NOT_ACTIVATED             BizCode = 403 // 账号未激活
	BizCode_USER_NOT_EXIST            BizCode = 404 // 用户不存在
	BizCode_CLOSED_ERROR              BizCode = 405 // 统一身份认证夜间不对外开放
	BizCode_AUTH_ERROR                BizCode = 406 // 密码错误
	BizCode_USER_ALREADY_EXIST        BizCode = 407 // 用户已经存在
)

// Enum value maps for BizCode.
var (
	BizCode_name = map[int32]string{
		0:   "OK",
		500: "UNKNOWN_ERROR",
		501: "PARAM_ERROR",
		401: "PASSWORD_LENGTH_ERROR",
		402: "WRONG_PASSWORD_OR_ACCOUNT",
		403: "NOT_ACTIVATED",
		404: "USER_NOT_EXIST",
		405: "CLOSED_ERROR",
		406: "AUTH_ERROR",
		407: "USER_ALREADY_EXIST",
	}
	BizCode_value = map[string]int32{
		"OK":                        0,
		"UNKNOWN_ERROR":             500,
		"PARAM_ERROR":               501,
		"PASSWORD_LENGTH_ERROR":     401,
		"WRONG_PASSWORD_OR_ACCOUNT": 402,
		"NOT_ACTIVATED":             403,
		"USER_NOT_EXIST":            404,
		"CLOSED_ERROR":              405,
		"AUTH_ERROR":                406,
		"USER_ALREADY_EXIST":        407,
	}
)

func (x BizCode) Enum() *BizCode {
	p := new(BizCode)
	*p = x
	return p
}

func (x BizCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BizCode) Descriptor() protoreflect.EnumDescriptor {
	return file_user_common_excepton_proto_enumTypes[0].Descriptor()
}

func (BizCode) Type() protoreflect.EnumType {
	return &file_user_common_excepton_proto_enumTypes[0]
}

func (x BizCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BizCode.Descriptor instead.
func (BizCode) EnumDescriptor() ([]byte, []int) {
	return file_user_common_excepton_proto_rawDescGZIP(), []int{0}
}

var File_user_common_excepton_proto protoreflect.FileDescriptor

const file_user_common_excepton_proto_rawDesc = "" +
	"\n" +
	"\x1auser/common/excepton.proto\x12\x1bzjut.jh.common.exception.v1*\xd9\x01\n" +
	"\aBizCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x12\n" +
	"\rUNKNOWN_ERROR\x10\xf4\x03\x12\x10\n" +
	"\vPARAM_ERROR\x10\xf5\x03\x12\x1a\n" +
	"\x15PASSWORD_LENGTH_ERROR\x10\x91\x03\x12\x1e\n" +
	"\x19WRONG_PASSWORD_OR_ACCOUNT\x10\x92\x03\x12\x12\n" +
	"\rNOT_ACTIVATED\x10\x93\x03\x12\x13\n" +
	"\x0eUSER_NOT_EXIST\x10\x94\x03\x12\x11\n" +
	"\fCLOSED_ERROR\x10\x95\x03\x12\x0f\n" +
	"\n" +
	"AUTH_ERROR\x10\x96\x03\x12\x17\n" +
	"\x12USER_ALREADY_EXIST\x10\x97\x03BBZ@github.com/zjutjh/User-Center/common/exception/v1alpha1;v1alpha1b\x06proto3"

var (
	file_user_common_excepton_proto_rawDescOnce sync.Once
	file_user_common_excepton_proto_rawDescData []byte
)

func file_user_common_excepton_proto_rawDescGZIP() []byte {
	file_user_common_excepton_proto_rawDescOnce.Do(func() {
		file_user_common_excepton_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_common_excepton_proto_rawDesc), len(file_user_common_excepton_proto_rawDesc)))
	})
	return file_user_common_excepton_proto_rawDescData
}

var file_user_common_excepton_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_common_excepton_proto_goTypes = []any{
	(BizCode)(0), // 0: zjut.jh.common.exception.v1.BizCode
}
var file_user_common_excepton_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_common_excepton_proto_init() }
func file_user_common_excepton_proto_init() {
	if File_user_common_excepton_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_common_excepton_proto_rawDesc), len(file_user_common_excepton_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_common_excepton_proto_goTypes,
		DependencyIndexes: file_user_common_excepton_proto_depIdxs,
		EnumInfos:         file_user_common_excepton_proto_enumTypes,
	}.Build()
	File_user_common_excepton_proto = out.File
	file_user_common_excepton_proto_goTypes = nil
	file_user_common_excepton_proto_depIdxs = nil
}
