syntax = "proto3";

package zjut.jh.common.exception.v1;

option go_package = "github.com/zjutjh/User-Center/common/exception/v1alpha1;v1alpha1";

// 业务错误码枚举
enum BizCode {
    // 通用
    OK            = 0;
    UNKNOWN_ERROR = 500;  // 系统异常，请稍后重试!
    PARAM_ERROR   = 501;  // 参数错误

    // 用户相关
    PASSWORD_LENGTH_ERROR     = 401;  // 密码长度不符合要求
    WRONG_PASSWORD_OR_ACCOUNT = 402;  // 账号或密码错误
    NOT_ACTIVATED             = 403;  // 账号未激活
    USER_NOT_EXIST            = 404;  // 用户不存在
    CLOSED_ERROR              = 405;  // 统一身份认证夜间不对外开放
    AUTH_ERROR                = 406;  // 密码错误
    USER_ALREADY_EXIST        = 407;  // 用户已经存在
}