// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User 用户表
type User struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                           // 用户ID
	StudentID     string    `gorm:"column:student_id;not null;comment:学号" json:"student_id"`                                  // 学号
	Password      string    `gorm:"column:password;not null;comment:精弘总密码" json:"password"`                                   // 精弘总密码
	PhoneNum      string    `gorm:"column:phone_num;not null;comment:手机号(易校园绑定)" json:"phone_num"`                            // 手机号(易校园绑定)
	UserType      string    `gorm:"column:user_type;not null;comment:用户类型" json:"user_type"`                                  // 用户类型
	Email         string    `gorm:"column:email;not null;comment:邮箱" json:"email"`                                            // 邮箱
	DeviceID      string    `gorm:"column:device_id;not null;comment:易校园DeviceID" json:"device_id"`                           // 易校园DeviceID
	YxyUID        string    `gorm:"column:yxy_uid;not null;comment:易校园UID" json:"yxy_uid"`                                    // 易校园UID
	ZfPassword    string    `gorm:"column:zf_password;not null;comment:正方密码" json:"zf_password"`                              // 正方密码
	OauthPassword string    `gorm:"column:oauth_password;not null;comment:统一身份认证密码" json:"oauth_password"`                    // 统一身份认证密码
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"update_time"` // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
