// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	bind "github.com/zjutjh/User-Center/apps/user-api/internal/handler/bind"
	user "github.com/zjutjh/User-Center/apps/user-api/internal/handler/user"
	"github.com/zjutjh/User-Center/apps/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					// 绑定统一认证密码
					Method:  http.MethodPost,
					Path:    "/bind/oauth",
					Handler: bind.BindOauthHandler(serverCtx),
				},
				{
					// 绑定易校园账号
					Method:  http.MethodPost,
					Path:    "/bind/yxy",
					Handler: bind.BindYxyHandler(serverCtx),
				},
				{
					// 绑定正方密码
					Method:  http.MethodPost,
					Path:    "/bind/zf",
					Handler: bind.BindZfHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建学生账号
				Method:  http.MethodPost,
				Path:    "/create/student",
				Handler: user.CreateStudentHandler(serverCtx),
			},
			{
				// 密码登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginByPasswordHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					// 注销账号
					Method:  http.MethodPost,
					Path:    "/del",
					Handler: user.DelHandler(serverCtx),
				},
				{
					// 用户信息
					Method:  http.MethodPost,
					Path:    "/info",
					Handler: user.InfoHandler(serverCtx),
				},
				{
					// 重置密码
					Method:  http.MethodPost,
					Path:    "/repass",
					Handler: user.RepassHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user"),
	)
}
