// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	login "github.com/zjutjh/User-Center/apps/user-api/internal/handler/login"
	user "github.com/zjutjh/User-Center/apps/user-api/internal/handler/user"
	"github.com/zjutjh/User-Center/apps/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 小程序登录
				Method:  http.MethodPost,
				Path:    "/login/mini-program",
				Handler: login.LoginByMiniProgramHandler(serverCtx),
			},
			{
				// 统一登录
				Method:  http.MethodPost,
				Path:    "/login/oauth",
				Handler: login.LoginByOauthHandler(serverCtx),
			},
			{
				// 账号密码登录
				Method:  http.MethodPost,
				Path:    "/login/password",
				Handler: login.LoginByPasswordHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建学生账号
				Method:  http.MethodPost,
				Path:    "/create/student",
				Handler: user.CreateStudentHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					// 注销账号
					Method:  http.MethodPost,
					Path:    "/del",
					Handler: user.DelHandler(serverCtx),
				},
				{
					// 用户信息
					Method:  http.MethodPost,
					Path:    "/info",
					Handler: user.InfoHandler(serverCtx),
				},
				{
					// 重置密码
					Method:  http.MethodPost,
					Path:    "/repass",
					Handler: user.RepassHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/user"),
	)
}
