// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	user "github.com/zjutjh/User-Center/apps/user-api/internal/handler/user"
	"github.com/zjutjh/User-Center/apps/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/users"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuth},
			[]rest.Route{
				{
					// 绑定外部系统
					Method:  http.MethodPost,
					Path:    "/bind",
					Handler: user.BindHandler(serverCtx),
				},
				{
					// 当前登录用户
					Method:  http.MethodGet,
					Path:    "/me",
					Handler: user.MeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/users"),
	)
}
