// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStudent = "student"

// Student 学生信息表
type Student struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:记录ID" json:"id"`                           // 记录ID
	StudentID  string    `gorm:"column:student_id;not null;comment:学号" json:"student_id"`                                  // 学号
	IDCard     string    `gorm:"column:id_card;comment:身份证号" json:"id_card"`                                               // 身份证号
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"update_time"` // 更新时间
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
