// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package usercenterservice

import (
	"context"

	"github.com/zjutjh/User-Center/apps/user-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BindRequest             = pb.BindRequest
	BindResponse            = pb.BindResponse
	GetUserPasswordRequest  = pb.GetUserPasswordRequest
	GetUserPasswordResponse = pb.GetUserPasswordResponse
	HealthyCheckRequest     = pb.HealthyCheckRequest
	HealthyCheckResponse    = pb.HealthyCheckResponse
	LoginRequest            = pb.LoginRequest
	LoginResponse           = pb.LoginResponse
	RegisterRequest         = pb.RegisterRequest
	RegisterResponse        = pb.RegisterResponse

	UserCenterService interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Bind(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error)
		GetUserPassword(ctx context.Context, in *GetUserPasswordRequest, opts ...grpc.CallOption) (*GetUserPasswordResponse, error)
		HealthyCheck(ctx context.Context, in *HealthyCheckRequest, opts ...grpc.CallOption) (*HealthyCheckResponse, error)
	}

	defaultUserCenterService struct {
		cli zrpc.Client
	}
)

func NewUserCenterService(cli zrpc.Client) UserCenterService {
	return &defaultUserCenterService{
		cli: cli,
	}
}

func (m *defaultUserCenterService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := pb.NewUserCenterServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserCenterService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb.NewUserCenterServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserCenterService) Bind(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error) {
	client := pb.NewUserCenterServiceClient(m.cli.Conn())
	return client.Bind(ctx, in, opts...)
}

func (m *defaultUserCenterService) GetUserPassword(ctx context.Context, in *GetUserPasswordRequest, opts ...grpc.CallOption) (*GetUserPasswordResponse, error) {
	client := pb.NewUserCenterServiceClient(m.cli.Conn())
	return client.GetUserPassword(ctx, in, opts...)
}

func (m *defaultUserCenterService) HealthyCheck(ctx context.Context, in *HealthyCheckRequest, opts ...grpc.CallOption) (*HealthyCheckResponse, error) {
	client := pb.NewUserCenterServiceClient(m.cli.Conn())
	return client.HealthyCheck(ctx, in, opts...)
}
