// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/zjutjh/User-Center/apps/user-rpc/internal/logic"
	"github.com/zjutjh/User-Center/apps/user-rpc/internal/svc"
	"github.com/zjutjh/User-Center/apps/user-rpc/pb"
)

type UserCenterServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserCenterServiceServer
}

func NewUserCenterServiceServer(svcCtx *svc.ServiceContext) *UserCenterServiceServer {
	return &UserCenterServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServiceServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserCenterServiceServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserCenterServiceServer) Bind(ctx context.Context, in *pb.BindRequest) (*pb.BindResponse, error) {
	l := logic.NewBindLogic(ctx, s.svcCtx)
	return l.Bind(in)
}

func (s *UserCenterServiceServer) GetUserPassword(ctx context.Context, in *pb.GetUserPasswordRequest) (*pb.GetUserPasswordResponse, error) {
	l := logic.NewGetUserPasswordLogic(ctx, s.svcCtx)
	return l.GetUserPassword(in)
}

func (s *UserCenterServiceServer) HealthyCheck(ctx context.Context, in *pb.HealthyCheckRequest) (*pb.HealthyCheckResponse, error) {
	l := logic.NewHealthyCheckLogic(ctx, s.svcCtx)
	return l.HealthyCheck(in)
}
