// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/zjutjh/User-Center/apps/user-rpc/internal/logic"
	"github.com/zjutjh/User-Center/apps/user-rpc/internal/svc"
	"github.com/zjutjh/User-Center/apps/user-rpc/pb"
)

type UserCenterServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserCenterServiceServer
}

func NewUserCenterServiceServer(svcCtx *svc.ServiceContext) *UserCenterServiceServer {
	return &UserCenterServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServiceServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserCenterServiceServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserCenterServiceServer) ResetPassword(ctx context.Context, in *pb.ResetPasswordRequest) (*pb.ResetPasswordResponse, error) {
	l := logic.NewResetPasswordLogic(ctx, s.svcCtx)
	return l.ResetPassword(in)
}

func (s *UserCenterServiceServer) DeleteAccount(ctx context.Context, in *pb.DeleteAccountRequest) (*pb.DeleteAccountResponse, error) {
	l := logic.NewDeleteAccountLogic(ctx, s.svcCtx)
	return l.DeleteAccount(in)
}

func (s *UserCenterServiceServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoRequest) (*pb.GetUserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserCenterServiceServer) BindOauth(ctx context.Context, in *pb.BindOauthRequest) (*pb.BindOauthResponse, error) {
	l := logic.NewBindOauthLogic(ctx, s.svcCtx)
	return l.BindOauth(in)
}

func (s *UserCenterServiceServer) BindZf(ctx context.Context, in *pb.BindZfRequest) (*pb.BindZfResponse, error) {
	l := logic.NewBindZfLogic(ctx, s.svcCtx)
	return l.BindZf(in)
}

func (s *UserCenterServiceServer) BindYxy(ctx context.Context, in *pb.BindYxyRequest) (*pb.BindYxyResponse, error) {
	l := logic.NewBindYxyLogic(ctx, s.svcCtx)
	return l.BindYxy(in)
}

func (s *UserCenterServiceServer) GetUserPassword(ctx context.Context, in *pb.GetUserPasswordRequest) (*pb.GetUserPasswordResponse, error) {
	l := logic.NewGetUserPasswordLogic(ctx, s.svcCtx)
	return l.GetUserPassword(in)
}
