# 应用基础配置
app:
  name: "user-center" # 应用名称
  env: "dev" # 应用环境 dev|test|prod

# gRPC 服务配置
grpc_server:
  addr: ":8080"

# HTTP Gateway 服务配置
http_server:
  addr: ":8081"

# 应用业务日志配置
log:
  level: 4 # 日志级别 0: panic 1: fatal 2: error 3: warn 4: info 5: debug 6: trace
  # 仅在本地开发调试时打开
  # filename: "/dev/stdout"

# 数据库配置
db:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  database: "user_center"

# Redis 配置
redis:
  addrs:
    - "127.0.0.1:6379"
  db: 0
  password: ""
