// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BindInfo struct {
	Zf    bool `json:"zf"`
	Yxy   bool `json:"yxy"`
	Oauth bool `json:"oauth"`
}

type CreateStudentReq struct {
	StudentId string `json:"student_id"`
	Password  string `json:"password"`
	CardId    string `json:"card_id"`
	Email     string `json:"email,optional"`
}

type CreateStudentResp struct {
	UserId int64 `json:"user_id"`
}

type DeleteAccountReq struct {
	IdCard    string `json:"iid"`
	StudentId string `json:"stuid"`
}

type EmptyResp struct {
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type MiniProgramLoginReq struct {
	AppType string `json:"app_type"`
	Code    string `json:"code"`
}

type ResetPasswordReq struct {
	IdCard    string `json:"iid"`
	StudentId string `json:"stuid"`
	Password  string `json:"password"`
}

type UserInfo struct {
	Id         int64    `json:"id"`
	Username   string   `json:"username"`
	StudentId  string   `json:"student_id"`
	Bind       BindInfo `json:"bind"`
	UserType   string   `json:"user_type"`
	Email      string   `json:"email,optional"`
	PhoneNum   string   `json:"phone_num,optional"`
	CreateTime string   `json:"create_time"`
}

type UserResp struct {
	User UserInfo `json:"user"`
}
