// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BindReq struct {
	Type          string `json:"type"`
	DeviceId      string `json:"deviceId,optional"`
	YxyUid        string `json:"yxyUid,optional"`
	ZfPassword    string `json:"zfPassword,optional"`
	OauthPassword string `json:"oauthPassword,optional"`
}

type BindResp struct {
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserId int64 `json:"userId"`
}

type MeResp struct {
	UserId int64 `json:"userId"`
}

type RegisterReq struct {
	StudentId string `json:"studentId"`
	Password  string `json:"password"`
	CardId    string `json:"cardId"`
	Email     string `json:"email"`
}

type RegisterResp struct {
}
