// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BindInfo struct {
	Zf    bool `json:"zf"`
	Yxy   bool `json:"yxy"`
	Oauth bool `json:"oauth"`
}

type BindOauthReq struct {
	OauthPassword string `json:"oauth_password" validate:"required"`
}

type BindYxyReq struct {
	DeviceId string `json:"device_id" validate:"required"`
	YxyUid   string `json:"yxy_uid" validate:"required"`
}

type BindZfReq struct {
	ZfPassword string `json:"zf_password" validate:"required"`
}

type CreateStudentReq struct {
	StudentId string `json:"student_id" validate:"required"`
	Password  string `json:"password" validate:"required"`
	CardId    string `json:"card_id" validate:"required"`
	Email     string `json:"email,optional"`
}

type CreateStudentResp struct {
	UserId int64 `json:"user_id"`
}

type DeleteAccountReq struct {
	IdCard    string `json:"iid" validate:"required"`
	StudentId string `json:"stuid" validate:"required"`
}

type EmptyResp struct {
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type MiniProgramLoginReq struct {
	AppType string `json:"app_type" validate:"required"`
	Code    string `json:"code" validate:"required"`
}

type ResetPasswordReq struct {
	IdCard    string `json:"iid" validate:"required"`
	StudentId string `json:"stuid" validate:"required"`
	Password  string `json:"password" validate:"required"`
}

type UserInfo struct {
	Id         int64    `json:"id"`
	Username   string   `json:"username"`
	StudentId  string   `json:"student_id"`
	Bind       BindInfo `json:"bind"`
	UserType   string   `json:"user_type"`
	Email      string   `json:"email,optional"`
	PhoneNum   string   `json:"phone_num,optional"`
	CreateTime string   `json:"create_time"`
}

type UserResp struct {
	User UserInfo `json:"user"`
}
