// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1alpha1/user.proto

package v1alpha1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *structpb.Value        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Iid           string                 `protobuf:"bytes,3,opt,name=iid,proto3" json:"iid,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetIid() string {
	if x != nil {
		return x.Iid
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Iid           string                 `protobuf:"bytes,3,opt,name=iid,proto3" json:"iid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{3}
}

func (x *ResetPasswordRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResetPasswordRequest) GetIid() string {
	if x != nil {
		return x.Iid
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Iid           string                 `protobuf:"bytes,2,opt,name=iid,proto3" json:"iid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *DeleteRequest) GetIid() string {
	if x != nil {
		return x.Iid
	}
	return ""
}

var File_user_v1alpha1_user_proto protoreflect.FileDescriptor

const file_user_v1alpha1_user_proto_rawDesc = "" +
	"\n" +
	"\x18user/v1alpha1/user.proto\x12\x19zjut.jh.api.user.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"d\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x04data\"s\n" +
	"\x0fRegisterRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03iid\x18\x03 \x01(\tR\x03iid\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"H\n" +
	"\fLoginRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"b\n" +
	"\x14ResetPasswordRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03iid\x18\x03 \x01(\tR\x03iid\"?\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x10\n" +
	"\x03iid\x18\x02 \x01(\tR\x03iid2\xd7\x04\n" +
	"\x11UserCenterService\x12u\n" +
	"\bRegister\x12*.zjut.jh.api.user.v1alpha1.RegisterRequest\x1a#.zjut.jh.api.user.v1alpha1.Response\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/register\x12k\n" +
	"\x05Login\x12'.zjut.jh.api.user.v1alpha1.LoginRequest\x1a#.zjut.jh.api.user.v1alpha1.Response\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/auth\x12}\n" +
	"\rResetPassword\x12/.zjut.jh.api.user.v1alpha1.ResetPasswordRequest\x1a#.zjut.jh.api.user.v1alpha1.Response\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/repass\x12l\n" +
	"\x06Delete\x12(.zjut.jh.api.user.v1alpha1.DeleteRequest\x1a#.zjut.jh.api.user.v1alpha1.Response\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/api/del\x12q\n" +
	"\n" +
	"OauthLogin\x12'.zjut.jh.api.user.v1alpha1.LoginRequest\x1a#.zjut.jh.api.user.v1alpha1.Response\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/oauthBS\n" +
	"\x15org.jh.usercenter.apiP\x01Z8github.com/zjutjh/User-Center/api/user/v1alpha1;v1alpha1b\x06proto3"

var (
	file_user_v1alpha1_user_proto_rawDescOnce sync.Once
	file_user_v1alpha1_user_proto_rawDescData []byte
)

func file_user_v1alpha1_user_proto_rawDescGZIP() []byte {
	file_user_v1alpha1_user_proto_rawDescOnce.Do(func() {
		file_user_v1alpha1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1alpha1_user_proto_rawDesc), len(file_user_v1alpha1_user_proto_rawDesc)))
	})
	return file_user_v1alpha1_user_proto_rawDescData
}

var file_user_v1alpha1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_v1alpha1_user_proto_goTypes = []any{
	(*Response)(nil),             // 0: zjut.jh.api.user.v1alpha1.Response
	(*RegisterRequest)(nil),      // 1: zjut.jh.api.user.v1alpha1.RegisterRequest
	(*LoginRequest)(nil),         // 2: zjut.jh.api.user.v1alpha1.LoginRequest
	(*ResetPasswordRequest)(nil), // 3: zjut.jh.api.user.v1alpha1.ResetPasswordRequest
	(*DeleteRequest)(nil),        // 4: zjut.jh.api.user.v1alpha1.DeleteRequest
	(*structpb.Value)(nil),       // 5: google.protobuf.Value
}
var file_user_v1alpha1_user_proto_depIdxs = []int32{
	5, // 0: zjut.jh.api.user.v1alpha1.Response.data:type_name -> google.protobuf.Value
	1, // 1: zjut.jh.api.user.v1alpha1.UserCenterService.Register:input_type -> zjut.jh.api.user.v1alpha1.RegisterRequest
	2, // 2: zjut.jh.api.user.v1alpha1.UserCenterService.Login:input_type -> zjut.jh.api.user.v1alpha1.LoginRequest
	3, // 3: zjut.jh.api.user.v1alpha1.UserCenterService.ResetPassword:input_type -> zjut.jh.api.user.v1alpha1.ResetPasswordRequest
	4, // 4: zjut.jh.api.user.v1alpha1.UserCenterService.Delete:input_type -> zjut.jh.api.user.v1alpha1.DeleteRequest
	2, // 5: zjut.jh.api.user.v1alpha1.UserCenterService.OauthLogin:input_type -> zjut.jh.api.user.v1alpha1.LoginRequest
	0, // 6: zjut.jh.api.user.v1alpha1.UserCenterService.Register:output_type -> zjut.jh.api.user.v1alpha1.Response
	0, // 7: zjut.jh.api.user.v1alpha1.UserCenterService.Login:output_type -> zjut.jh.api.user.v1alpha1.Response
	0, // 8: zjut.jh.api.user.v1alpha1.UserCenterService.ResetPassword:output_type -> zjut.jh.api.user.v1alpha1.Response
	0, // 9: zjut.jh.api.user.v1alpha1.UserCenterService.Delete:output_type -> zjut.jh.api.user.v1alpha1.Response
	0, // 10: zjut.jh.api.user.v1alpha1.UserCenterService.OauthLogin:output_type -> zjut.jh.api.user.v1alpha1.Response
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1alpha1_user_proto_init() }
func file_user_v1alpha1_user_proto_init() {
	if File_user_v1alpha1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1alpha1_user_proto_rawDesc), len(file_user_v1alpha1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1alpha1_user_proto_goTypes,
		DependencyIndexes: file_user_v1alpha1_user_proto_depIdxs,
		MessageInfos:      file_user_v1alpha1_user_proto_msgTypes,
	}.Build()
	File_user_v1alpha1_user_proto = out.File
	file_user_v1alpha1_user_proto_goTypes = nil
	file_user_v1alpha1_user_proto_depIdxs = nil
}
