// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1alpha1/common.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 业务错误码枚举
type BizCode int32

const (
	// 通用
	BizCode_OK           BizCode = 0
	BizCode_UnknownError BizCode = 10000 // 系统异常，请稍后重试!
	// 用户相关
	BizCode_PasswordLengthError    BizCode = 40001 // 密码长度不符合要求
	BizCode_WrongAccountOrPassword BizCode = 40002 // 账号或密码错误
	BizCode_NotActivated           BizCode = 40003 // 账号未激活
	BizCode_UserNotExist           BizCode = 40004 // 用户不存在
	BizCode_ClosedError            BizCode = 40005 // 统一身份认证夜间不对外开放
	BizCode_UserExisted            BizCode = 40006 // 用户已经存在
)

// Enum value maps for BizCode.
var (
	BizCode_name = map[int32]string{
		0:     "OK",
		10000: "UnknownError",
		40001: "PasswordLengthError",
		40002: "WrongAccountOrPassword",
		40003: "NotActivated",
		40004: "UserNotExist",
		40005: "ClosedError",
		40006: "UserExisted",
	}
	BizCode_value = map[string]int32{
		"OK":                     0,
		"UnknownError":           10000,
		"PasswordLengthError":    40001,
		"WrongAccountOrPassword": 40002,
		"NotActivated":           40003,
		"UserNotExist":           40004,
		"ClosedError":            40005,
		"UserExisted":            40006,
	}
)

func (x BizCode) Enum() *BizCode {
	p := new(BizCode)
	*p = x
	return p
}

func (x BizCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BizCode) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1alpha1_common_proto_enumTypes[0].Descriptor()
}

func (BizCode) Type() protoreflect.EnumType {
	return &file_user_v1alpha1_common_proto_enumTypes[0]
}

func (x BizCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BizCode.Descriptor instead.
func (BizCode) EnumDescriptor() ([]byte, []int) {
	return file_user_v1alpha1_common_proto_rawDescGZIP(), []int{0}
}

var File_user_v1alpha1_common_proto protoreflect.FileDescriptor

const file_user_v1alpha1_common_proto_rawDesc = "" +
	"\n" +
	"\x1auser/v1alpha1/common.proto\x12\x1bzjut.jh.usercenter.v1alpha1*\xab\x01\n" +
	"\aBizCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x11\n" +
	"\fUnknownError\x10\x90N\x12\x19\n" +
	"\x13PasswordLengthError\x10\xc1\xb8\x02\x12\x1c\n" +
	"\x16WrongAccountOrPassword\x10¸\x02\x12\x12\n" +
	"\fNotActivated\x10ø\x02\x12\x12\n" +
	"\fUserNotExist\x10ĸ\x02\x12\x11\n" +
	"\vClosedError\x10Ÿ\x02\x12\x11\n" +
	"\vUserExisted\x10Ƹ\x02B:Z8github.com/zjutjh/User-Center/idl/user/v1alpha1;v1alpha1b\x06proto3"

var (
	file_user_v1alpha1_common_proto_rawDescOnce sync.Once
	file_user_v1alpha1_common_proto_rawDescData []byte
)

func file_user_v1alpha1_common_proto_rawDescGZIP() []byte {
	file_user_v1alpha1_common_proto_rawDescOnce.Do(func() {
		file_user_v1alpha1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1alpha1_common_proto_rawDesc), len(file_user_v1alpha1_common_proto_rawDesc)))
	})
	return file_user_v1alpha1_common_proto_rawDescData
}

var file_user_v1alpha1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1alpha1_common_proto_goTypes = []any{
	(BizCode)(0), // 0: zjut.jh.usercenter.v1alpha1.BizCode
}
var file_user_v1alpha1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1alpha1_common_proto_init() }
func file_user_v1alpha1_common_proto_init() {
	if File_user_v1alpha1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1alpha1_common_proto_rawDesc), len(file_user_v1alpha1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1alpha1_common_proto_goTypes,
		DependencyIndexes: file_user_v1alpha1_common_proto_depIdxs,
		EnumInfos:         file_user_v1alpha1_common_proto_enumTypes,
	}.Build()
	File_user_v1alpha1_common_proto = out.File
	file_user_v1alpha1_common_proto_goTypes = nil
	file_user_v1alpha1_common_proto_depIdxs = nil
}
