// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user/v1alpha1/user.proto

package v1alpha1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          BizCode                `protobuf:"varint,1,opt,name=code,proto3,enum=zjut.jh.usercenter.v1alpha1.BizCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetCode() BizCode {
	if x != nil {
		return x.Code
	}
	return BizCode_OK
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Iid           string                 `protobuf:"bytes,3,opt,name=iid,proto3" json:"iid,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetIid() string {
	if x != nil {
		return x.Iid
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Iid           string                 `protobuf:"bytes,3,opt,name=iid,proto3" json:"iid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{3}
}

func (x *ResetPasswordRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResetPasswordRequest) GetIid() string {
	if x != nil {
		return x.Iid
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Iid           string                 `protobuf:"bytes,2,opt,name=iid,proto3" json:"iid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *DeleteRequest) GetIid() string {
	if x != nil {
		return x.Iid
	}
	return ""
}

type HealthyCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthyCheckRequest) Reset() {
	*x = HealthyCheckRequest{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthyCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthyCheckRequest) ProtoMessage() {}

func (x *HealthyCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthyCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthyCheckRequest) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{5}
}

func (x *HealthyCheckRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          BizCode                `protobuf:"varint,1,opt,name=code,proto3,enum=zjut.jh.usercenter.v1alpha1.BizCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetCode() BizCode {
	if x != nil {
		return x.Code
	}
	return BizCode_OK
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          BizCode                `protobuf:"varint,1,opt,name=code,proto3,enum=zjut.jh.usercenter.v1alpha1.BizCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{7}
}

func (x *ResetPasswordResponse) GetCode() BizCode {
	if x != nil {
		return x.Code
	}
	return BizCode_OK
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          BizCode                `protobuf:"varint,1,opt,name=code,proto3,enum=zjut.jh.usercenter.v1alpha1.BizCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetCode() BizCode {
	if x != nil {
		return x.Code
	}
	return BizCode_OK
}

type OauthLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          BizCode                `protobuf:"varint,1,opt,name=code,proto3,enum=zjut.jh.usercenter.v1alpha1.BizCode" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=studentId,proto3" json:"studentId,omitempty"`
	UserType      string                 `protobuf:"bytes,4,opt,name=userType,proto3" json:"userType,omitempty"`
	UserTypeDesc  string                 `protobuf:"bytes,5,opt,name=userTypeDesc,proto3" json:"userTypeDesc,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthLoginResponse) Reset() {
	*x = OauthLoginResponse{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthLoginResponse) ProtoMessage() {}

func (x *OauthLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthLoginResponse.ProtoReflect.Descriptor instead.
func (*OauthLoginResponse) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{9}
}

func (x *OauthLoginResponse) GetCode() BizCode {
	if x != nil {
		return x.Code
	}
	return BizCode_OK
}

func (x *OauthLoginResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OauthLoginResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *OauthLoginResponse) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *OauthLoginResponse) GetUserTypeDesc() string {
	if x != nil {
		return x.UserTypeDesc
	}
	return ""
}

func (x *OauthLoginResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *OauthLoginResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type HealthyCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          BizCode                `protobuf:"varint,1,opt,name=code,proto3,enum=zjut.jh.usercenter.v1alpha1.BizCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthyCheckResponse) Reset() {
	*x = HealthyCheckResponse{}
	mi := &file_user_v1alpha1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthyCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthyCheckResponse) ProtoMessage() {}

func (x *HealthyCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1alpha1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthyCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthyCheckResponse) Descriptor() ([]byte, []int) {
	return file_user_v1alpha1_user_proto_rawDescGZIP(), []int{10}
}

func (x *HealthyCheckResponse) GetCode() BizCode {
	if x != nil {
		return x.Code
	}
	return BizCode_OK
}

var File_user_v1alpha1_user_proto protoreflect.FileDescriptor

const file_user_v1alpha1_user_proto_rawDesc = "" +
	"\n" +
	"\x18user/v1alpha1/user.proto\x12\x1bzjut.jh.usercenter.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x1auser/v1alpha1/common.proto\"H\n" +
	"\fLoginRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"I\n" +
	"\rLoginResponse\x128\n" +
	"\x04code\x18\x01 \x01(\x0e2$.zjut.jh.usercenter.v1alpha1.BizCodeR\x04code\"s\n" +
	"\x0fRegisterRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03iid\x18\x03 \x01(\tR\x03iid\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"b\n" +
	"\x14ResetPasswordRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03iid\x18\x03 \x01(\tR\x03iid\"?\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x10\n" +
	"\x03iid\x18\x02 \x01(\tR\x03iid\"3\n" +
	"\x13HealthyCheckRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\"L\n" +
	"\x10RegisterResponse\x128\n" +
	"\x04code\x18\x01 \x01(\x0e2$.zjut.jh.usercenter.v1alpha1.BizCodeR\x04code\"Q\n" +
	"\x15ResetPasswordResponse\x128\n" +
	"\x04code\x18\x01 \x01(\x0e2$.zjut.jh.usercenter.v1alpha1.BizCodeR\x04code\"J\n" +
	"\x0eDeleteResponse\x128\n" +
	"\x04code\x18\x01 \x01(\x0e2$.zjut.jh.usercenter.v1alpha1.BizCodeR\x04code\"\xf0\x01\n" +
	"\x12OauthLoginResponse\x128\n" +
	"\x04code\x18\x01 \x01(\x0e2$.zjut.jh.usercenter.v1alpha1.BizCodeR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tstudentId\x18\x03 \x01(\tR\tstudentId\x12\x1a\n" +
	"\buserType\x18\x04 \x01(\tR\buserType\x12\"\n" +
	"\fuserTypeDesc\x18\x05 \x01(\tR\fuserTypeDesc\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\"P\n" +
	"\x14HealthyCheckResponse\x128\n" +
	"\x04code\x18\x01 \x01(\x0e2$.zjut.jh.usercenter.v1alpha1.BizCodeR\x04code2\x96\x05\n" +
	"\x11UserCenterService\x12g\n" +
	"\bRegister\x12,.zjut.jh.usercenter.v1alpha1.RegisterRequest\x1a-.zjut.jh.usercenter.v1alpha1.RegisterResponse\x12^\n" +
	"\x05Login\x12).zjut.jh.usercenter.v1alpha1.LoginRequest\x1a*.zjut.jh.usercenter.v1alpha1.LoginResponse\x12v\n" +
	"\rResetPassword\x121.zjut.jh.usercenter.v1alpha1.ResetPasswordRequest\x1a2.zjut.jh.usercenter.v1alpha1.ResetPasswordResponse\x12a\n" +
	"\x06Delete\x12*.zjut.jh.usercenter.v1alpha1.DeleteRequest\x1a+.zjut.jh.usercenter.v1alpha1.DeleteResponse\x12h\n" +
	"\n" +
	"OauthLogin\x12).zjut.jh.usercenter.v1alpha1.LoginRequest\x1a/.zjut.jh.usercenter.v1alpha1.OauthLoginResponse\x12s\n" +
	"\fHealthyCheck\x120.zjut.jh.usercenter.v1alpha1.HealthyCheckRequest\x1a1.zjut.jh.usercenter.v1alpha1.HealthyCheckResponseBS\n" +
	"\x15org.jh.usercenter.apiP\x01Z8github.com/zjutjh/User-Center/idl/user/v1alpha1;v1alpha1b\x06proto3"

var (
	file_user_v1alpha1_user_proto_rawDescOnce sync.Once
	file_user_v1alpha1_user_proto_rawDescData []byte
)

func file_user_v1alpha1_user_proto_rawDescGZIP() []byte {
	file_user_v1alpha1_user_proto_rawDescOnce.Do(func() {
		file_user_v1alpha1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1alpha1_user_proto_rawDesc), len(file_user_v1alpha1_user_proto_rawDesc)))
	})
	return file_user_v1alpha1_user_proto_rawDescData
}

var file_user_v1alpha1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_v1alpha1_user_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: zjut.jh.usercenter.v1alpha1.LoginRequest
	(*LoginResponse)(nil),         // 1: zjut.jh.usercenter.v1alpha1.LoginResponse
	(*RegisterRequest)(nil),       // 2: zjut.jh.usercenter.v1alpha1.RegisterRequest
	(*ResetPasswordRequest)(nil),  // 3: zjut.jh.usercenter.v1alpha1.ResetPasswordRequest
	(*DeleteRequest)(nil),         // 4: zjut.jh.usercenter.v1alpha1.DeleteRequest
	(*HealthyCheckRequest)(nil),   // 5: zjut.jh.usercenter.v1alpha1.HealthyCheckRequest
	(*RegisterResponse)(nil),      // 6: zjut.jh.usercenter.v1alpha1.RegisterResponse
	(*ResetPasswordResponse)(nil), // 7: zjut.jh.usercenter.v1alpha1.ResetPasswordResponse
	(*DeleteResponse)(nil),        // 8: zjut.jh.usercenter.v1alpha1.DeleteResponse
	(*OauthLoginResponse)(nil),    // 9: zjut.jh.usercenter.v1alpha1.OauthLoginResponse
	(*HealthyCheckResponse)(nil),  // 10: zjut.jh.usercenter.v1alpha1.HealthyCheckResponse
	(BizCode)(0),                  // 11: zjut.jh.usercenter.v1alpha1.BizCode
}
var file_user_v1alpha1_user_proto_depIdxs = []int32{
	11, // 0: zjut.jh.usercenter.v1alpha1.LoginResponse.code:type_name -> zjut.jh.usercenter.v1alpha1.BizCode
	11, // 1: zjut.jh.usercenter.v1alpha1.RegisterResponse.code:type_name -> zjut.jh.usercenter.v1alpha1.BizCode
	11, // 2: zjut.jh.usercenter.v1alpha1.ResetPasswordResponse.code:type_name -> zjut.jh.usercenter.v1alpha1.BizCode
	11, // 3: zjut.jh.usercenter.v1alpha1.DeleteResponse.code:type_name -> zjut.jh.usercenter.v1alpha1.BizCode
	11, // 4: zjut.jh.usercenter.v1alpha1.OauthLoginResponse.code:type_name -> zjut.jh.usercenter.v1alpha1.BizCode
	11, // 5: zjut.jh.usercenter.v1alpha1.HealthyCheckResponse.code:type_name -> zjut.jh.usercenter.v1alpha1.BizCode
	2,  // 6: zjut.jh.usercenter.v1alpha1.UserCenterService.Register:input_type -> zjut.jh.usercenter.v1alpha1.RegisterRequest
	0,  // 7: zjut.jh.usercenter.v1alpha1.UserCenterService.Login:input_type -> zjut.jh.usercenter.v1alpha1.LoginRequest
	3,  // 8: zjut.jh.usercenter.v1alpha1.UserCenterService.ResetPassword:input_type -> zjut.jh.usercenter.v1alpha1.ResetPasswordRequest
	4,  // 9: zjut.jh.usercenter.v1alpha1.UserCenterService.Delete:input_type -> zjut.jh.usercenter.v1alpha1.DeleteRequest
	0,  // 10: zjut.jh.usercenter.v1alpha1.UserCenterService.OauthLogin:input_type -> zjut.jh.usercenter.v1alpha1.LoginRequest
	5,  // 11: zjut.jh.usercenter.v1alpha1.UserCenterService.HealthyCheck:input_type -> zjut.jh.usercenter.v1alpha1.HealthyCheckRequest
	6,  // 12: zjut.jh.usercenter.v1alpha1.UserCenterService.Register:output_type -> zjut.jh.usercenter.v1alpha1.RegisterResponse
	1,  // 13: zjut.jh.usercenter.v1alpha1.UserCenterService.Login:output_type -> zjut.jh.usercenter.v1alpha1.LoginResponse
	7,  // 14: zjut.jh.usercenter.v1alpha1.UserCenterService.ResetPassword:output_type -> zjut.jh.usercenter.v1alpha1.ResetPasswordResponse
	8,  // 15: zjut.jh.usercenter.v1alpha1.UserCenterService.Delete:output_type -> zjut.jh.usercenter.v1alpha1.DeleteResponse
	9,  // 16: zjut.jh.usercenter.v1alpha1.UserCenterService.OauthLogin:output_type -> zjut.jh.usercenter.v1alpha1.OauthLoginResponse
	10, // 17: zjut.jh.usercenter.v1alpha1.UserCenterService.HealthyCheck:output_type -> zjut.jh.usercenter.v1alpha1.HealthyCheckResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_user_v1alpha1_user_proto_init() }
func file_user_v1alpha1_user_proto_init() {
	if File_user_v1alpha1_user_proto != nil {
		return
	}
	file_user_v1alpha1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1alpha1_user_proto_rawDesc), len(file_user_v1alpha1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1alpha1_user_proto_goTypes,
		DependencyIndexes: file_user_v1alpha1_user_proto_depIdxs,
		MessageInfos:      file_user_v1alpha1_user_proto_msgTypes,
	}.Build()
	File_user_v1alpha1_user_proto = out.File
	file_user_v1alpha1_user_proto_goTypes = nil
	file_user_v1alpha1_user_proto_depIdxs = nil
}
