syntax = "proto3";

package zjut.jh.usercenter.v1alpha1;

option go_package = "github.com/zjutjh/User-Center/idl/user/v1alpha1;v1alpha1";
option java_multiple_files = true;
option java_package = "org.jh.usercenter.api";

import "google/api/annotations.proto";
import "user/v1alpha1/common.proto";

message LoginRequest {
    string studentId = 1;
    string password = 2;
}

message LoginResponse {
    BizCode code = 1;
}

message RegisterRequest {
    string studentId = 1;
    string password = 2;
    string iid = 3;
    string email = 4;
}

message ResetPasswordRequest {
    string studentId = 1;
    string password = 2;
    string iid = 3;
}

message DeleteRequest {
    string studentId = 1;
    string iid = 2;
}

message HealthyCheckRequest {
    string studentId = 1;
}

message RegisterResponse {
    BizCode code = 1;
}



message ResetPasswordResponse {
    BizCode code = 1;
}

message DeleteResponse {
    BizCode code = 1;
}

message OauthLoginResponse {
    BizCode code = 1;
    string name = 2;
    string studentId = 3;
    string userType = 4;
    string userTypeDesc = 5;
    string gender = 6;
    string avatar = 7;
}

message HealthyCheckResponse {
    BizCode code = 1;
}

service UserCenterService {
    // 注册接口
    rpc Register(RegisterRequest) returns (RegisterResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
    rpc Delete(DeleteRequest) returns (DeleteResponse);
    rpc OauthLogin(LoginRequest) returns (OauthLoginResponse);
    rpc HealthyCheck(HealthyCheckRequest) returns (HealthyCheckResponse);
}