// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCollege = "college"

// College 学院表
type College struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:学院ID" json:"id"`                           // 学院ID
	CollegeCode string    `gorm:"column:college_code;not null;comment:学院代码" json:"college_code"`                            // 学院代码
	CollegeName string    `gorm:"column:college_name;not null;comment:学院名称" json:"college_name"`                            // 学院名称
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"update_time"` // 更新时间
}

// TableName College's table name
func (*College) TableName() string {
	return TableNameCollege
}
