// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMiniProgramUser = "mini_program_user"

// MiniProgramUser 快捷登录表
type MiniProgramUser struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                           // 用户ID
	StudentID  string    `gorm:"column:student_id;not null;comment:学号" json:"student_id"`                                  // 学号
	AppType    string    `gorm:"column:app_type;not null;comment:应用类型" json:"app_type"`                                    // 应用类型
	OpenID     string    `gorm:"column:open_id;not null;comment:open_id" json:"open_id"`                                   // open_id
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"update_time"` // 更新时间
}

// TableName MiniProgramUser's table name
func (*MiniProgramUser) TableName() string {
	return TableNameMiniProgramUser
}
