// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: apps/user-rpc/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindType int32

const (
	BindType_BIND_TYPE_UNSPECIFIED BindType = 0
	BindType_BIND_TYPE_YXY         BindType = 1
	BindType_BIND_TYPE_ZF          BindType = 2
	BindType_BIND_TYPE_OAUTH       BindType = 3
)

// Enum value maps for BindType.
var (
	BindType_name = map[int32]string{
		0: "BIND_TYPE_UNSPECIFIED",
		1: "BIND_TYPE_YXY",
		2: "BIND_TYPE_ZF",
		3: "BIND_TYPE_OAUTH",
	}
	BindType_value = map[string]int32{
		"BIND_TYPE_UNSPECIFIED": 0,
		"BIND_TYPE_YXY":         1,
		"BIND_TYPE_ZF":          2,
		"BIND_TYPE_OAUTH":       3,
	}
)

func (x BindType) Enum() *BindType {
	p := new(BindType)
	*p = x
	return p
}

func (x BindType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindType) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_user_rpc_user_proto_enumTypes[0].Descriptor()
}

func (BindType) Type() protoreflect.EnumType {
	return &file_apps_user_rpc_user_proto_enumTypes[0]
}

func (x BindType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindType.Descriptor instead.
func (BindType) EnumDescriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CardId        string                 `protobuf:"bytes,3,opt,name=cardId,proto3" json:"cardId,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{3}
}

type BindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Type          BindType               `protobuf:"varint,2,opt,name=type,proto3,enum=user.BindType" json:"type,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	YxyUid        string                 `protobuf:"bytes,4,opt,name=yxy_uid,json=yxyUid,proto3" json:"yxy_uid,omitempty"`
	ZfPassword    string                 `protobuf:"bytes,5,opt,name=zf_password,json=zfPassword,proto3" json:"zf_password,omitempty"`
	OauthPassword string                 `protobuf:"bytes,6,opt,name=oauth_password,json=oauthPassword,proto3" json:"oauth_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *BindRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BindRequest) GetType() BindType {
	if x != nil {
		return x.Type
	}
	return BindType_BIND_TYPE_UNSPECIFIED
}

func (x *BindRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *BindRequest) GetYxyUid() string {
	if x != nil {
		return x.YxyUid
	}
	return ""
}

func (x *BindRequest) GetZfPassword() string {
	if x != nil {
		return x.ZfPassword
	}
	return ""
}

func (x *BindRequest) GetOauthPassword() string {
	if x != nil {
		return x.OauthPassword
	}
	return ""
}

type BindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindResponse) Reset() {
	*x = BindResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResponse) ProtoMessage() {}

func (x *BindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResponse.ProtoReflect.Descriptor instead.
func (*BindResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{5}
}

type GetUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPasswordRequest) Reset() {
	*x = GetUserPasswordRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPasswordRequest) ProtoMessage() {}

func (x *GetUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*GetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserPasswordRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	YxyUid        string                 `protobuf:"bytes,3,opt,name=yxy_uid,json=yxyUid,proto3" json:"yxy_uid,omitempty"`
	ZfPassword    string                 `protobuf:"bytes,4,opt,name=zf_password,json=zfPassword,proto3" json:"zf_password,omitempty"`
	OauthPassword string                 `protobuf:"bytes,5,opt,name=oauth_password,json=oauthPassword,proto3" json:"oauth_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPasswordResponse) Reset() {
	*x = GetUserPasswordResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPasswordResponse) ProtoMessage() {}

func (x *GetUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*GetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserPasswordResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetUserPasswordResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetUserPasswordResponse) GetYxyUid() string {
	if x != nil {
		return x.YxyUid
	}
	return ""
}

func (x *GetUserPasswordResponse) GetZfPassword() string {
	if x != nil {
		return x.ZfPassword
	}
	return ""
}

func (x *GetUserPasswordResponse) GetOauthPassword() string {
	if x != nil {
		return x.OauthPassword
	}
	return ""
}

type HealthyCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthyCheckRequest) Reset() {
	*x = HealthyCheckRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthyCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthyCheckRequest) ProtoMessage() {}

func (x *HealthyCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthyCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthyCheckRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *HealthyCheckRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type HealthyCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthyCheckResponse) Reset() {
	*x = HealthyCheckResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthyCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthyCheckResponse) ProtoMessage() {}

func (x *HealthyCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthyCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthyCheckResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{9}
}

var File_apps_user_rpc_user_proto protoreflect.FileDescriptor

const file_apps_user_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x18apps/user-rpc/user.proto\x12\x04user\"H\n" +
	"\fLoginRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"'\n" +
	"\rLoginResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"y\n" +
	"\x0fRegisterRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x16\n" +
	"\x06cardId\x18\x03 \x01(\tR\x06cardId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\x12\n" +
	"\x10RegisterResponse\"\xc7\x01\n" +
	"\vBindRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\"\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0e.user.BindTypeR\x04type\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x17\n" +
	"\ayxy_uid\x18\x04 \x01(\tR\x06yxyUid\x12\x1f\n" +
	"\vzf_password\x18\x05 \x01(\tR\n" +
	"zfPassword\x12%\n" +
	"\x0eoauth_password\x18\x06 \x01(\tR\roauthPassword\"\x0e\n" +
	"\fBindResponse\"0\n" +
	"\x16GetUserPasswordRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\xb6\x01\n" +
	"\x17GetUserPasswordResponse\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x17\n" +
	"\ayxy_uid\x18\x03 \x01(\tR\x06yxyUid\x12\x1f\n" +
	"\vzf_password\x18\x04 \x01(\tR\n" +
	"zfPassword\x12%\n" +
	"\x0eoauth_password\x18\x05 \x01(\tR\roauthPassword\"3\n" +
	"\x13HealthyCheckRequest\x12\x1c\n" +
	"\tstudentId\x18\x01 \x01(\tR\tstudentId\"\x16\n" +
	"\x14HealthyCheckResponse*_\n" +
	"\bBindType\x12\x19\n" +
	"\x15BIND_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rBIND_TYPE_YXY\x10\x01\x12\x10\n" +
	"\fBIND_TYPE_ZF\x10\x02\x12\x13\n" +
	"\x0fBIND_TYPE_OAUTH\x10\x032\xc6\x02\n" +
	"\x11UserCenterService\x129\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12-\n" +
	"\x04Bind\x12\x11.user.BindRequest\x1a\x12.user.BindResponse\x12N\n" +
	"\x0fGetUserPassword\x12\x1c.user.GetUserPasswordRequest\x1a\x1d.user.GetUserPasswordResponse\x12E\n" +
	"\fHealthyCheck\x12\x19.user.HealthyCheckRequest\x1a\x1a.user.HealthyCheckResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_apps_user_rpc_user_proto_rawDescOnce sync.Once
	file_apps_user_rpc_user_proto_rawDescData []byte
)

func file_apps_user_rpc_user_proto_rawDescGZIP() []byte {
	file_apps_user_rpc_user_proto_rawDescOnce.Do(func() {
		file_apps_user_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_user_rpc_user_proto_rawDesc), len(file_apps_user_rpc_user_proto_rawDesc)))
	})
	return file_apps_user_rpc_user_proto_rawDescData
}

var file_apps_user_rpc_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_user_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_apps_user_rpc_user_proto_goTypes = []any{
	(BindType)(0),                   // 0: user.BindType
	(*LoginRequest)(nil),            // 1: user.LoginRequest
	(*LoginResponse)(nil),           // 2: user.LoginResponse
	(*RegisterRequest)(nil),         // 3: user.RegisterRequest
	(*RegisterResponse)(nil),        // 4: user.RegisterResponse
	(*BindRequest)(nil),             // 5: user.BindRequest
	(*BindResponse)(nil),            // 6: user.BindResponse
	(*GetUserPasswordRequest)(nil),  // 7: user.GetUserPasswordRequest
	(*GetUserPasswordResponse)(nil), // 8: user.GetUserPasswordResponse
	(*HealthyCheckRequest)(nil),     // 9: user.HealthyCheckRequest
	(*HealthyCheckResponse)(nil),    // 10: user.HealthyCheckResponse
}
var file_apps_user_rpc_user_proto_depIdxs = []int32{
	0,  // 0: user.BindRequest.type:type_name -> user.BindType
	3,  // 1: user.UserCenterService.Register:input_type -> user.RegisterRequest
	1,  // 2: user.UserCenterService.Login:input_type -> user.LoginRequest
	5,  // 3: user.UserCenterService.Bind:input_type -> user.BindRequest
	7,  // 4: user.UserCenterService.GetUserPassword:input_type -> user.GetUserPasswordRequest
	9,  // 5: user.UserCenterService.HealthyCheck:input_type -> user.HealthyCheckRequest
	4,  // 6: user.UserCenterService.Register:output_type -> user.RegisterResponse
	2,  // 7: user.UserCenterService.Login:output_type -> user.LoginResponse
	6,  // 8: user.UserCenterService.Bind:output_type -> user.BindResponse
	8,  // 9: user.UserCenterService.GetUserPassword:output_type -> user.GetUserPasswordResponse
	10, // 10: user.UserCenterService.HealthyCheck:output_type -> user.HealthyCheckResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_apps_user_rpc_user_proto_init() }
func file_apps_user_rpc_user_proto_init() {
	if File_apps_user_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_user_rpc_user_proto_rawDesc), len(file_apps_user_rpc_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_user_rpc_user_proto_goTypes,
		DependencyIndexes: file_apps_user_rpc_user_proto_depIdxs,
		EnumInfos:         file_apps_user_rpc_user_proto_enumTypes,
		MessageInfos:      file_apps_user_rpc_user_proto_msgTypes,
	}.Build()
	File_apps_user_rpc_user_proto = out.File
	file_apps_user_rpc_user_proto_goTypes = nil
	file_apps_user_rpc_user_proto_depIdxs = nil
}
