// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: apps/user-rpc/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CardId        string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{3}
}

type BindOauthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OauthPassword string                 `protobuf:"bytes,2,opt,name=oauth_password,json=oauthPassword,proto3" json:"oauth_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindOauthRequest) Reset() {
	*x = BindOauthRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindOauthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindOauthRequest) ProtoMessage() {}

func (x *BindOauthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindOauthRequest.ProtoReflect.Descriptor instead.
func (*BindOauthRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *BindOauthRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BindOauthRequest) GetOauthPassword() string {
	if x != nil {
		return x.OauthPassword
	}
	return ""
}

type BindOauthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindOauthResponse) Reset() {
	*x = BindOauthResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindOauthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindOauthResponse) ProtoMessage() {}

func (x *BindOauthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindOauthResponse.ProtoReflect.Descriptor instead.
func (*BindOauthResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{5}
}

type BindZfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ZfPassword    string                 `protobuf:"bytes,2,opt,name=zf_password,json=zfPassword,proto3" json:"zf_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindZfRequest) Reset() {
	*x = BindZfRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindZfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindZfRequest) ProtoMessage() {}

func (x *BindZfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindZfRequest.ProtoReflect.Descriptor instead.
func (*BindZfRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *BindZfRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BindZfRequest) GetZfPassword() string {
	if x != nil {
		return x.ZfPassword
	}
	return ""
}

type BindZfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindZfResponse) Reset() {
	*x = BindZfResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindZfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindZfResponse) ProtoMessage() {}

func (x *BindZfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindZfResponse.ProtoReflect.Descriptor instead.
func (*BindZfResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{7}
}

type BindYxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	YxyUid        string                 `protobuf:"bytes,3,opt,name=yxy_uid,json=yxyUid,proto3" json:"yxy_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindYxyRequest) Reset() {
	*x = BindYxyRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindYxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindYxyRequest) ProtoMessage() {}

func (x *BindYxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindYxyRequest.ProtoReflect.Descriptor instead.
func (*BindYxyRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *BindYxyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BindYxyRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *BindYxyRequest) GetYxyUid() string {
	if x != nil {
		return x.YxyUid
	}
	return ""
}

type BindYxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindYxyResponse) Reset() {
	*x = BindYxyResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindYxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindYxyResponse) ProtoMessage() {}

func (x *BindYxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindYxyResponse.ProtoReflect.Descriptor instead.
func (*BindYxyResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{9}
}

type GetUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPasswordRequest) Reset() {
	*x = GetUserPasswordRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPasswordRequest) ProtoMessage() {}

func (x *GetUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*GetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserPasswordRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	YxyUid        string                 `protobuf:"bytes,3,opt,name=yxy_uid,json=yxyUid,proto3" json:"yxy_uid,omitempty"`
	ZfPassword    string                 `protobuf:"bytes,4,opt,name=zf_password,json=zfPassword,proto3" json:"zf_password,omitempty"`
	OauthPassword string                 `protobuf:"bytes,5,opt,name=oauth_password,json=oauthPassword,proto3" json:"oauth_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPasswordResponse) Reset() {
	*x = GetUserPasswordResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPasswordResponse) ProtoMessage() {}

func (x *GetUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*GetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserPasswordResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetUserPasswordResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetUserPasswordResponse) GetYxyUid() string {
	if x != nil {
		return x.YxyUid
	}
	return ""
}

func (x *GetUserPasswordResponse) GetZfPassword() string {
	if x != nil {
		return x.ZfPassword
	}
	return ""
}

func (x *GetUserPasswordResponse) GetOauthPassword() string {
	if x != nil {
		return x.OauthPassword
	}
	return ""
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	UserType      string                 `protobuf:"bytes,3,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNum      string                 `protobuf:"bytes,5,opt,name=phone_num,json=phoneNum,proto3" json:"phone_num,omitempty"`
	DeviceId      string                 `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	YxyUid        string                 `protobuf:"bytes,7,opt,name=yxy_uid,json=yxyUid,proto3" json:"yxy_uid,omitempty"`
	ZfPassword    string                 `protobuf:"bytes,8,opt,name=zf_password,json=zfPassword,proto3" json:"zf_password,omitempty"`
	OauthPassword string                 `protobuf:"bytes,9,opt,name=oauth_password,json=oauthPassword,proto3" json:"oauth_password,omitempty"`
	CreateTime    string                 `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserInfoResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInfoResponse) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetUserInfoResponse) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *GetUserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserInfoResponse) GetPhoneNum() string {
	if x != nil {
		return x.PhoneNum
	}
	return ""
}

func (x *GetUserInfoResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetUserInfoResponse) GetYxyUid() string {
	if x != nil {
		return x.YxyUid
	}
	return ""
}

func (x *GetUserInfoResponse) GetZfPassword() string {
	if x != nil {
		return x.ZfPassword
	}
	return ""
}

func (x *GetUserInfoResponse) GetOauthPassword() string {
	if x != nil {
		return x.OauthPassword
	}
	return ""
}

func (x *GetUserInfoResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CardId        string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{14}
}

func (x *ResetPasswordRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ResetPasswordRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ResetPasswordRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{15}
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CardId        string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteAccountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteAccountRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *DeleteAccountRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{17}
}

type HealthyCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthyCheckRequest) Reset() {
	*x = HealthyCheckRequest{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthyCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthyCheckRequest) ProtoMessage() {}

func (x *HealthyCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthyCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthyCheckRequest) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{18}
}

func (x *HealthyCheckRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type HealthyCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthyCheckResponse) Reset() {
	*x = HealthyCheckResponse{}
	mi := &file_apps_user_rpc_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthyCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthyCheckResponse) ProtoMessage() {}

func (x *HealthyCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthyCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthyCheckResponse) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{19}
}

var File_apps_user_rpc_user_proto protoreflect.FileDescriptor

const file_apps_user_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x18apps/user-rpc/user.proto\x12\x04user\"I\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"B\n" +
	"\rLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\"{\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\x12\n" +
	"\x10RegisterResponse\"R\n" +
	"\x10BindOauthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12%\n" +
	"\x0eoauth_password\x18\x02 \x01(\tR\roauthPassword\"\x13\n" +
	"\x11BindOauthResponse\"I\n" +
	"\rBindZfRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vzf_password\x18\x02 \x01(\tR\n" +
	"zfPassword\"\x10\n" +
	"\x0eBindZfResponse\"_\n" +
	"\x0eBindYxyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x17\n" +
	"\ayxy_uid\x18\x03 \x01(\tR\x06yxyUid\"\x11\n" +
	"\x0fBindYxyResponse\"1\n" +
	"\x16GetUserPasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xb6\x01\n" +
	"\x17GetUserPasswordResponse\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x17\n" +
	"\ayxy_uid\x18\x03 \x01(\tR\x06yxyUid\x12\x1f\n" +
	"\vzf_password\x18\x04 \x01(\tR\n" +
	"zfPassword\x12%\n" +
	"\x0eoauth_password\x18\x05 \x01(\tR\roauthPassword\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xbc\x02\n" +
	"\x13GetUserInfoResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tuser_type\x18\x03 \x01(\tR\buserType\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1b\n" +
	"\tphone_num\x18\x05 \x01(\tR\bphoneNum\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\x12\x17\n" +
	"\ayxy_uid\x18\a \x01(\tR\x06yxyUid\x12\x1f\n" +
	"\vzf_password\x18\b \x01(\tR\n" +
	"zfPassword\x12%\n" +
	"\x0eoauth_password\x18\t \x01(\tR\roauthPassword\x12\x1f\n" +
	"\vcreate_time\x18\n" +
	" \x01(\tR\n" +
	"createTime\"\x83\x01\n" +
	"\x14ResetPasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x17\n" +
	"\x15ResetPasswordResponse\"g\n" +
	"\x14DeleteAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\"\x17\n" +
	"\x15DeleteAccountResponse\"4\n" +
	"\x13HealthyCheckRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"\x16\n" +
	"\x14HealthyCheckResponse2\x9a\x05\n" +
	"\x11UserCenterService\x129\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12<\n" +
	"\tBindOauth\x12\x16.user.BindOauthRequest\x1a\x17.user.BindOauthResponse\x123\n" +
	"\x06BindZf\x12\x13.user.BindZfRequest\x1a\x14.user.BindZfResponse\x126\n" +
	"\aBindYxy\x12\x14.user.BindYxyRequest\x1a\x15.user.BindYxyResponse\x12N\n" +
	"\x0fGetUserPassword\x12\x1c.user.GetUserPasswordRequest\x1a\x1d.user.GetUserPasswordResponse\x12B\n" +
	"\vGetUserInfo\x12\x18.user.GetUserInfoRequest\x1a\x19.user.GetUserInfoResponse\x12H\n" +
	"\rResetPassword\x12\x1a.user.ResetPasswordRequest\x1a\x1b.user.ResetPasswordResponse\x12H\n" +
	"\rDeleteAccount\x12\x1a.user.DeleteAccountRequest\x1a\x1b.user.DeleteAccountResponse\x12E\n" +
	"\fHealthyCheck\x12\x19.user.HealthyCheckRequest\x1a\x1a.user.HealthyCheckResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_apps_user_rpc_user_proto_rawDescOnce sync.Once
	file_apps_user_rpc_user_proto_rawDescData []byte
)

func file_apps_user_rpc_user_proto_rawDescGZIP() []byte {
	file_apps_user_rpc_user_proto_rawDescOnce.Do(func() {
		file_apps_user_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_user_rpc_user_proto_rawDesc), len(file_apps_user_rpc_user_proto_rawDesc)))
	})
	return file_apps_user_rpc_user_proto_rawDescData
}

var file_apps_user_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_apps_user_rpc_user_proto_goTypes = []any{
	(*LoginRequest)(nil),            // 0: user.LoginRequest
	(*LoginResponse)(nil),           // 1: user.LoginResponse
	(*RegisterRequest)(nil),         // 2: user.RegisterRequest
	(*RegisterResponse)(nil),        // 3: user.RegisterResponse
	(*BindOauthRequest)(nil),        // 4: user.BindOauthRequest
	(*BindOauthResponse)(nil),       // 5: user.BindOauthResponse
	(*BindZfRequest)(nil),           // 6: user.BindZfRequest
	(*BindZfResponse)(nil),          // 7: user.BindZfResponse
	(*BindYxyRequest)(nil),          // 8: user.BindYxyRequest
	(*BindYxyResponse)(nil),         // 9: user.BindYxyResponse
	(*GetUserPasswordRequest)(nil),  // 10: user.GetUserPasswordRequest
	(*GetUserPasswordResponse)(nil), // 11: user.GetUserPasswordResponse
	(*GetUserInfoRequest)(nil),      // 12: user.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),     // 13: user.GetUserInfoResponse
	(*ResetPasswordRequest)(nil),    // 14: user.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),   // 15: user.ResetPasswordResponse
	(*DeleteAccountRequest)(nil),    // 16: user.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),   // 17: user.DeleteAccountResponse
	(*HealthyCheckRequest)(nil),     // 18: user.HealthyCheckRequest
	(*HealthyCheckResponse)(nil),    // 19: user.HealthyCheckResponse
}
var file_apps_user_rpc_user_proto_depIdxs = []int32{
	2,  // 0: user.UserCenterService.Register:input_type -> user.RegisterRequest
	0,  // 1: user.UserCenterService.Login:input_type -> user.LoginRequest
	4,  // 2: user.UserCenterService.BindOauth:input_type -> user.BindOauthRequest
	6,  // 3: user.UserCenterService.BindZf:input_type -> user.BindZfRequest
	8,  // 4: user.UserCenterService.BindYxy:input_type -> user.BindYxyRequest
	10, // 5: user.UserCenterService.GetUserPassword:input_type -> user.GetUserPasswordRequest
	12, // 6: user.UserCenterService.GetUserInfo:input_type -> user.GetUserInfoRequest
	14, // 7: user.UserCenterService.ResetPassword:input_type -> user.ResetPasswordRequest
	16, // 8: user.UserCenterService.DeleteAccount:input_type -> user.DeleteAccountRequest
	18, // 9: user.UserCenterService.HealthyCheck:input_type -> user.HealthyCheckRequest
	3,  // 10: user.UserCenterService.Register:output_type -> user.RegisterResponse
	1,  // 11: user.UserCenterService.Login:output_type -> user.LoginResponse
	5,  // 12: user.UserCenterService.BindOauth:output_type -> user.BindOauthResponse
	7,  // 13: user.UserCenterService.BindZf:output_type -> user.BindZfResponse
	9,  // 14: user.UserCenterService.BindYxy:output_type -> user.BindYxyResponse
	11, // 15: user.UserCenterService.GetUserPassword:output_type -> user.GetUserPasswordResponse
	13, // 16: user.UserCenterService.GetUserInfo:output_type -> user.GetUserInfoResponse
	15, // 17: user.UserCenterService.ResetPassword:output_type -> user.ResetPasswordResponse
	17, // 18: user.UserCenterService.DeleteAccount:output_type -> user.DeleteAccountResponse
	19, // 19: user.UserCenterService.HealthyCheck:output_type -> user.HealthyCheckResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_apps_user_rpc_user_proto_init() }
func file_apps_user_rpc_user_proto_init() {
	if File_apps_user_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_user_rpc_user_proto_rawDesc), len(file_apps_user_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_user_rpc_user_proto_goTypes,
		DependencyIndexes: file_apps_user_rpc_user_proto_depIdxs,
		MessageInfos:      file_apps_user_rpc_user_proto_msgTypes,
	}.Build()
	File_apps_user_rpc_user_proto = out.File
	file_apps_user_rpc_user_proto_goTypes = nil
	file_apps_user_rpc_user_proto_depIdxs = nil
}
