syntax = "proto3";

package user;

option go_package = "./pb";

message LoginRequest {
    string student_id = 1;
    string password = 2;
}

message LoginResponse {
    int64 user_id = 1;
    string session = 2;
}

message RegisterRequest {
    string student_id = 1;
    string password = 2;
    string card_id = 3;
    string email = 4;
}

message RegisterResponse {
}

message BindOauthRequest {
    int64 user_id = 1;
    string oauth_password = 2;
}

message BindOauthResponse {
}

message BindZfRequest {
    int64 user_id = 1;
    string zf_password = 2;
}

message BindZfResponse {
}

message BindYxyRequest {
    int64 user_id = 1;
    string device_id = 2;
    string yxy_uid = 3;
}

message BindYxyResponse {
}

message GetUserPasswordRequest {
    int64 user_id = 1;
}

message GetUserPasswordResponse {
    string student_id = 1;
    string device_id = 2;
    string yxy_uid = 3;
    string zf_password = 4;
    string oauth_password = 5;
}

message GetUserInfoRequest {
    int64 user_id = 1;
}

message GetUserInfoResponse {
    int64 user_id = 1;
    string student_id = 2;
    string user_type = 3;
    string email = 4;
    string phone_num = 5;
    string device_id = 6;
    string yxy_uid = 7;
    string zf_password = 8;
    string oauth_password = 9;
    string create_time = 10;
}

message ResetPasswordRequest {
    int64 user_id = 1;
    string student_id = 2;
    string card_id = 3;
    string password = 4;
}

message ResetPasswordResponse {
}

message DeleteAccountRequest {
    int64 user_id = 1;
    string student_id = 2;
    string card_id = 3;
}

message DeleteAccountResponse {
}

message HealthyCheckRequest {
    string student_id = 1;
}

message HealthyCheckResponse {
}

service UserCenterService {
    rpc Register(RegisterRequest) returns (RegisterResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc BindOauth(BindOauthRequest) returns (BindOauthResponse);
    rpc BindZf(BindZfRequest) returns (BindZfResponse);
    rpc BindYxy(BindYxyRequest) returns (BindYxyResponse);
    rpc GetUserPassword(GetUserPasswordRequest) returns (GetUserPasswordResponse);
    rpc GetUserInfo(GetUserInfoRequest) returns (GetUserInfoResponse);
    rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
    rpc DeleteAccount(DeleteAccountRequest) returns (DeleteAccountResponse);
    rpc HealthyCheck(HealthyCheckRequest) returns (HealthyCheckResponse);
}
