syntax = "proto3";

package user;

option go_package = "./pb";

enum BindType {
    BIND_TYPE_UNSPECIFIED = 0;
    BIND_TYPE_OAUTH = 1;
    BIND_TYPE_ZF = 2;
    BIND_TYPE_YXY = 3;
}

message LoginRequest {
    string studentId = 1;
    string password = 2;
}

message LoginResponse {
    int64 userId = 1;
    string session = 2;
}

message RegisterRequest {
    string studentId = 1;
    string password = 2;
    string cardId = 3;
    string email = 4;
}

message RegisterResponse {
}

message BindRequest {
    int64 userId = 1;
    BindType type = 2;
    string device_id = 3;
    string yxy_uid = 4;
    string zf_password = 5;
    string oauth_password = 6;
}

message BindResponse {
}

message GetUserPasswordRequest {
    int64 userId = 1;
}

message GetUserPasswordResponse {
    string student_id = 1;
    string device_id = 2;
    string yxy_uid = 3;
    string zf_password = 4;
    string oauth_password = 5;
}

message GetUserInfoRequest {
    int64 userId = 1;
}

message GetUserInfoResponse {
    int64 user_id = 1;
    string student_id = 2;
    string user_type = 3;
    string email = 4;
    string phone_num = 5;
    string device_id = 6;
    string yxy_uid = 7;
    string zf_password = 8;
    string oauth_password = 9;
    string create_time = 10;
}

message ResetPasswordRequest {
    int64 userId = 1;
    string studentId = 2;
    string cardId = 3;
    string password = 4;
}

message ResetPasswordResponse {
}

message DeleteAccountRequest {
    int64 userId = 1;
    string studentId = 2;
    string cardId = 3;
}

message DeleteAccountResponse {
}

message HealthyCheckRequest {
    string studentId = 1;
}

message HealthyCheckResponse {
}

service UserCenterService {
    rpc Register(RegisterRequest) returns (RegisterResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc Bind(BindRequest) returns (BindResponse);
    rpc GetUserPassword(GetUserPasswordRequest) returns (GetUserPasswordResponse);
    rpc GetUserInfo(GetUserInfoRequest) returns (GetUserInfoResponse);
    rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
    rpc DeleteAccount(DeleteAccountRequest) returns (DeleteAccountResponse);
    rpc HealthyCheck(HealthyCheckRequest) returns (HealthyCheckResponse);
}
